Presentation/UTEP.Web/Areas/Admin/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UTEP.Web.Areas.Admin.Models.CompanyViewModels;
using UTEP.Data.Domain.Models.Tables.CompanyBasedGroup;
using UTEP.Core.UnitOfWork.Persistence;
using Microsoft.EntityFrameworkCore;
using UTEP.Data;
using UTEP.Settings;
using UTEP.Web.Attribute;
using Microsoft.AspNetCore.Mvc.Rendering;
using UTEP.Data.Domain.Models.Tables.UserBasedGroup;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using UTEP.Web.Areas.Admin.Models.UserViewModels;
using UTEP.Data.Domain.Models.Tables.RoleBasedGroup;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using UTEP.Web.Services;
using Microsoft.AspNetCore.Hosting;

namespace UTEP.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    [Route("[area]/{lang:lang}/[controller]/[action]/{id?}")]
    public class CompanyController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<Role> _roleManager;
        private readonly UnitOfWork _unitOfWork;
        private readonly ILogger _logger;
        private readonly IFileProcessor _fileService;
        private readonly IEmailSender _emailSender;

        public CompanyController(
            DbContextOptions<UTEPDbContext> contextOptions,
            UserManager<User> userManager,
            RoleManager<Role> roleManager,
            ILoggerFactory loggerFactory,
            IEmailSender emailSender,
            IFileProcessor fileService
            )
        {
            _unitOfWork = new UnitOfWork(new UTEPDbContext(contextOptions));
            _userManager = userManager;
            _roleManager = roleManager;
            _logger = loggerFactory.CreateLogger<UserController>();
            _fileService = fileService;
            _emailSender = emailSender;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [AjaxOnly]
        public IActionResult LoadData()
        {
            var draw = HttpContext.Request.Form["draw"].FirstOrDefault();
            var start = Request.Form["start"].FirstOrDefault();
            var length = Request.Form["length"].FirstOrDefault();
            var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
            var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
            var searchValue = Request.Form["search[value]"].FirstOrDefault();

            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;

            var list = _unitOfWork.Companies.FindDataTable(x => x.Status == Status.Active && x.TypeOfCompany == TypeOfCompany.Carrier, "az", skip, pageSize, sortColumn, sortColumnDirection, searchValue);
            return Json(new { draw = draw, recordsFiltered = list.RecordsFiltered, recordsTotal = list.RecordsTotal, data = list.Data });
        }

        [HttpGet]
        public IActionResult Create()
        {
            var model = new CreateCompanyViewModel
            {
                CompanyTypes = _unitOfWork.CompanyTypes.Find(x => x.Status == Status.Active).Select(y => new SelectListItem
                {
                    Value = y.Id.ToString(),
                    Text = y.Name
                })
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateCompanyViewModel model, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                if (_userManager.Users.Any(x => x.Email == model.CreateUsers.Email))
                {
                    ModelState.AddModelError("", $"{model.CompanyEmail} emaili artıq mövcuddur.");
                    return View(model);
                }
                if (_unitOfWork.Companies.Find(x => x.TypeOfCompany == TypeOfCompany.Carrier).Any(x => x.Email == model.CompanyEmail))
                {
                    ModelState.AddModelError("", $"{model.CompanyEmail} emaili artıq mövcuddur.");
                    return View(model);
                }
                if (_unitOfWork.Companies.Find(x => x.TypeOfCompany == TypeOfCompany.Carrier).Any(x => x.Name == model.CompanyName))
                {
                    ModelState.AddModelError("", $"{model.CompanyName} adı artıq mövcuddur.");
                    return View(model);
                }

                var user = new User
                {
                    UserName = model.CreateUsers.Email,
                    Email = model.CreateUsers.Email,
                    FirstName = model.CreateUsers.FirstName,
                    LastName = model.CreateUsers.LastName,
                    PhoneNumber = model.CreateUsers.PhoneNumber,
                    TypeOfUser = TypeOfUsers.CompanyConfirmed,
                    Company = new Company
                    {
                        CompanyTypeId = model.CompanyTypeId,
                        TaxIdentificationNumber = Guid.NewGuid().ToString(),
                        TypeOfCompany = TypeOfCompany.Carrier,
                        Name = model.CompanyName,
                        Email = model.CompanyEmail,
                        Phone = model.CompanyPhone,
                        LocationLatitude = 0m,
                        LocationLongitude = 0m,
                        Address = model.CompanyAddress,
                        VOEN = model.VOEN
                    },
                    EmailConfirmed = true
                };
                if (file.Length > 0 && !string.IsNullOrEmpty(file.Name))
                {
                    var extensions = new string[] { ".jpg", ".jpeg", "png" };
                    var folder = $"\\company\\logos\\";
                    user.Company.Logo = await _fileService.UploadFileAsync(file, folder, extensions);
                }

                try
                {
                    var role = await _roleManager.FindByNameAsync("Manager");
                    user.Roles.Add(new IdentityUserRole<long>
                    {
                        UserId = user.Id,
                        RoleId = role.Id
                    });
                    var result = await _userManager.CreateAsync(user, model.CreateUsers.Password);

                    if (result.Succeeded)
                    {
                        _logger.LogInformation(3, "User created a new account with password.");

                        var message = $"<!DOCTYPE html><html lang='az'><head> <meta charset='UTF-8'> <title>UTEP</title></head><body style='text-align:center;'> <table> <tr> <td align='center'> <img src='http://utep.a2hosted.com/logo/ULogoNew2.png' alt='UTEP' style='width:60px; height:60px;'> </td></tr><tr> <td style='font-size: 18px'> <h3 align='center'> UTEP-ə qatıldığınız üçün şadıq! </h3> <p> Siz artıq elanlarınızı saytda yerləşdirə bilərsiniz. </p> <p> Sayta giriş üçün emailiniz: <b> {model.CompanyEmail} </b>, şifrəniz: <b> {model.CreateUsers.Password} </b> </br>. </p><p> Unutmayın, siz istənilən zaman <a href='mailto:support@utep.az'>support@utep.az</a> emaili vasitəsilə bizə müraciət edə bilərsiniz. Biz UTEP.az servisi haqda sizin bütün suallarınıza cavab verməyə hazırıq. </p><br><hr> </td></tr><tr> <td align='center' style='font-size: 14px'> <p> Cəfər Cabbarlı küçəsi, 44, Bakı, Azərbaycan </p><p> <a href='tel:+994777779696'> +994 77 777 96 96</a> <br><a href='mailto:support@utep.az'>support@utep.az</a> </p></td></tr></table></body></html>";
                        await _emailSender.SendEmailAsync(model.CompanyEmail, "UTEP profiliniz haqqında məlumat!", message);

                        return RedirectToAction(nameof(Index), new { id = "" });
                    }
                    AddErrors(result);

                }
                catch (Exception)
                {
                    throw;
                }
            }

            model.CompanyTypes = _unitOfWork.CompanyTypes.Find(x => x.Status == Status.Active).Select(y => new SelectListItem
            {
                Value = y.Id.ToString(),
                Text = y.Name
            });
            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(long id)
        {
            var company = _unitOfWork.Companies.GetWithUser(x => x.Id == id && x.Status == Status.Active);
            if (company != null)
            {
                var model = new EditCompanyViewModel
                {
                    Id = company.Id,
                    CompanyName = company.Name,
                    CompanyEmail = company.Email,
                    CompanyPhone = company.Phone,
                    OldCompanyName = company.Name,
                    OldCompanyEmail = company.Email,
                    OldUserEmail = company.User.Email,
                    //Fax = company.Fax,
                    //TypeOfCompany=company.TypeOfCompany,
                    CompanyAddress = company.Address,
                    CompanyTypeId = company.CompanyTypeId,
                    LogoPath = company.Logo,
                    CompanyTypes = _unitOfWork.CompanyTypes.Find(x => x.Status == Status.Active).Select(y => new SelectListItem
                    {
                        Value = y.Id.ToString(),
                        Text = y.Name
                    }),
                    EditUser = new EditUserViewModel
                    {
                        Id = company.User.Id,
                        FirstName = company.User.FirstName,
                        LastName = company.User.LastName,
                        Email = company.User.Email,
                        PhoneNumber = company.User.PhoneNumber,
                        UserGroupId = company.User.UserGroupId

Presentation/UTEP.Web/Areas/Admin/Views/Company/Create.cshtml
@model UTEP.Web.Areas.Admin.Models.CompanyViewModels.CreateCompanyViewModel

@{
    ViewData["Title"] = "Company Yeni";
}



@*@Html.AntiForgeryToken()*@

<div class="row">
    <div class="col-md-offset-2 col-md-8">
        <div class="profile-content">
            <div class="row">
                <div class="col-md-12">
                    <div class="portlet light bordered">
                        <div class="portlet-title tabbable-line">
                            <div class="caption caption-md">
                                <i class="icon-globe theme-font hide"></i>
                                <span class="caption-subject font-blue-madison bold uppercase">Yeni</span>
                            </div>
                            <ul class="nav nav-tabs">
                                <li class="active">
                                    <a href="#tab_1_1" data-toggle="tab">Daşıyıcı Şirkət</a>
                                </li>
                            </ul>
                        </div>
                        <div class="portlet-body">
                            <div class="tab-content">
                                <div class="tab-pane active" id="tab_1_1">

                                    <form asp-controller="Company" asp-action="create" asp-area="admin" method="post" enctype="multipart/form-data">
                                        <div asp-validation-summary="All" class="text-danger"></div>
                                        <h2 class="text-center">Şirkət</h2>
                                        <div class="form-group">
                                            <label class="control-label">Şirkət Adı</label>
                                            <input asp-for="CompanyName" class="form-control" required />
                                            <span asp-validation-for="CompanyName" class="text-danger" required></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Şirkət Emaili</label>
                                            <input asp-for="CompanyEmail" class="form-control" required />
                                            <span asp-validation-for="CompanyEmail" class="text-danger" required></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Şirkət Telefonu</label>
                                            <input asp-for="CompanyPhone" class="form-control" required />
                                            <span asp-validation-for="CompanyPhone" class="text-danger" required></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Şirkət Addresi</label>
                                            <input asp-for="CompanyAddress" asp-is-invariant="true" class="form-control" required />
                                            <span asp-validation-for="CompanyAddress" class="text-danger" required></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">VOEN</label>
                                            <input asp-for="VOEN" class="form-control" />
                                            <span asp-validation-for="VOEN" class="text-danger" required></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Şirkət Logosu</label>
                                            <input type="file" id="logo" name="file" onchange="UploadPhoto(this)" class="form-control" accept="image/*" required />
                                            @*<span asp-validation-for="Fax" class="text-danger" required></span>*@
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Company tipi</label>
                                            <select asp-for="CompanyTypeId" asp-items="Model.CompanyTypes" class="form-control" required>
                                                <option value="">...</option>
                                            </select>
                                            <span asp-validation-for="CompanyTypeId" class="text-danger" required></span>
                                        </div>

                                        <h2 class="text-center">Menecer</h2>

                                        <div class="form-group">
                                            <label class="control-label">Adı</label>
                                            <input asp-for="CreateUsers.FirstName" class="form-control" />
                                            <span asp-validation-for="CreateUsers.FirstName" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Soyadı</label>
                                            <input asp-for="CreateUsers.LastName" class="form-control" />
                                            <span asp-validation-for="CreateUsers.LastName" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Email</label>
                                            <input asp-for="CreateUsers.Email" class="form-control" />
                                            <span asp-validation-for="CreateUsers.Email" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Şifrə</label>
                                            <input asp-for="CreateUsers.Password" class="form-control" />
                                            <span asp-validation-for="CreateUsers.Password" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Şifr təkrar</label>
                                            <input asp-for="CreateUsers.ConfirmPassword" class="form-control" />
                                            <span asp-validation-for="CreateUsers.ConfirmPassword" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Telefon nömrəsi</label>
                                            <input asp-for="CreateUsers.PhoneNumber" class="form-control">
                                            <span asp-validation-for="CreateUsers.PhoneNumber" class="text-danger"></span>
                                        </div>


                                        <div class="form-actions">
                                            <div class="row">
                                                <div class="text-right col-md-12">
                                                    <button id="btn-validate-spinner" type="button" class="btn green">Submit</button>
                                                    <a asp-area="Admin" asp-controller="Company" asp-action="Index" asp-route-id="" class="btn default">Ləğv et</a>
                                                </div>
                                            </div>
                                        </div>
                                        @*<input type="hidden" asp-for="@Model.UserId" />*@
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts{
    <script src="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/datatables.min.js"></script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        function UploadPhoto(inp) {
            if (inp.files && inp.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#logo + img').remove();
                    $('#logo').after('<img src= "' + e.target.result + '" width="100" height="100" style="text-align:center;" />');
                }
                reader.readAsDataURL(inp.files[0]);
            }
        }
    </script>
}

Presentation/UTEP.Web/Areas/Admin/Views/Company/Edit.cshtml
@model UTEP.Web.Areas.Admin.Models.CompanyViewModels.EditCompanyViewModel

@{
    ViewData["Title"] = "Company Edit";
}



@*@Html.AntiForgeryToken()*@

<div class="row">
    <div class="col-md-offset-2 col-md-8">
        <div class="profile-content">
            <div class="row">
                <div class="col-md-12">
                    <div class="portlet light bordered">
                        <div class="portlet-title tabbable-line">
                            <div class="caption caption-md">
                                <i class="icon-globe theme-font hide"></i>
                                <span class="caption-subject font-blue-madison bold uppercase">Edit</span>
                            </div>
                            <ul class="nav nav-tabs">
                                <li class="active">
                                    <a href="#tab_1_1" data-toggle="tab">Company</a>
                                </li>
                            </ul>
                        </div>
                        <div class="portlet-body">
                            <div class="tab-content">
                                <div class="tab-pane active" id="tab_1_1">

                                    <form asp-controller="Company" asp-action="Edit" asp-area="admin" method="post">
                                        <div asp-validation-summary="All" class="text-danger"></div>
                                        <div class="form-group">
                                            <label class="control-label">Şirkət Adı</label>
                                            <input asp-for="CompanyName" class="form-control" required />
                                            <span asp-validation-for="CompanyName" class="text-danger" required></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Şirkət Emali</label>
                                            <input asp-for="CompanyEmail" class="form-control" required />
                                            <span asp-validation-for="CompanyEmail" class="text-danger" required></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Şirkət Telefonu</label>
                                            <input asp-for="CompanyPhone" class="form-control" required />
                                            <span asp-validation-for="CompanyPhone" class="text-danger" required></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Şirkət Adresi</label>
                                            <input asp-for="CompanyAddress" asp-is-invariant="true" class="form-control" required />
                                            <span asp-validation-for="CompanyAddress" class="text-danger" required></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Şirkət Logosu</label>
                                            <input asp-for="Logo" type="file" onchange="UploadPhoto.call(this)" class="form-control" />
                                            @*<span asp-validation-for="Fax" class="text-danger" required></span>*@
                                        </div>
                                        <div style="text-align:center;">
                                            <img src="~/uploads/company/logo/@Model.Logo" id="logo" alt="Company Logo" style="height:100px;" />
                                        </div>


                                        <div class="form-group">
                                            <label class="control-label">Company tipi</label>
                                            <select asp-for="CompanyTypeId" asp-items="Model.CompanyTypes" class="form-control" required>
                                                <option value="">...</option>
                                            </select>
                                            <span asp-validation-for="CompanyTypeId" class="text-danger" required></span>
                                        </div>


                                        <div class="form-group">
                                            <label class="control-label">Adı</label>
                                            <input asp-for="EditUser.FirstName" class="form-control" />
                                            <span asp-validation-for="EditUser.FirstName" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Soyadı</label>
                                            <input asp-for="EditUser.LastName" class="form-control" />
                                            <span asp-validation-for="EditUser.LastName" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Email</label>
                                            <input asp-for="EditUser.Email" class="form-control" />
                                            <span asp-validation-for="EditUser.Email" class="text-danger"></span>
                                        </div>

                                        <div class="form-group">
                                            <label class="control-label">Telefon nömrəsi</label>
                                            <input asp-for="EditUser.PhoneNumber" class="form-control">
                                            <span asp-validation-for="EditUser.PhoneNumber" class="text-danger"></span>
                                        </div>

                                        <input type="hidden" asp-for="OldCompanyEmail" />
                                        <input type="hidden" asp-for="OldCompanyName" />
                                        <input type="hidden" asp-for="OldUserEmail" />


                                        <div class="form-actions">
                                            <div class="row">
                                                <div class="text-right col-md-12">
                                                    <button id="btn-validate-spinner" type="button" class="btn green">Submit</button>
                                                    <a asp-area="Admin" asp-controller="Company" asp-action="Index" asp-route-id="" class="btn default">Ləğv et</a>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts{
    <script src="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/datatables.min.js"></script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        function UploadPhoto() {
            if (this.files && this.files[0]) {
                var obj = new FileReader();
                obj.onload = function (data) {
                    var image = document.getElementById("logo");
                    image.src = data.target.result;
                }
                obj.readAsDataURL(this.files[0]);
            }
        }
    </script>
}

Presentation/UTEP.Web/Areas/Admin/Views/Company/Index.cshtml
@{
    ViewData["Title"] = "Ana Sehife";
}

<title></title>


@section Styles{ <link href="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" />

    <link href="~/Plugins/DataTables/DataTables-1.10.18/css/dataTables.bootstrap4.css" rel="stylesheet" />

}
@section Scripts{
    <script src="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/datatables.min.js"></script>
    <script src="~/Plugins/DataTables/DataTables-1.10.18/js/jquery.dataTables.js"></script>
    <script src="~/Plugins/DataTables/DataTables-1.10.18/js/dataTables.bootstrap4.js"></script>
    <script src="~/js/date/formatdate.js"></script>
    <script src="~/js/admin/company.js"></script>
}

<div class="row margin-top-10">
    <div class="col-md-12 text-center">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fas fa-building font-dark"></i>
                    <span class="caption-subject bold">
                        Şirkət
                        <a asp-controller="Company" asp-action="Create" class="btn blue  btn-xs  btn-outline">
                            New <i class="fa fa-plus"></i>
                        </a>
                        <a asp-controller="Company" asp-action="Trash" class="btn red  btn-xs  btn-outline">
                            Trash <i class="fa fa-times"></i>
                        </a>
                    </span>
                </div>
                <div class="tools"> </div>
            </div>
            <div class="portlet-body">
                <table id="companyIndexTable" class="table table-hover table-striped table-bordered nowrap text-center" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th class="text-center"><b>Şirkət Adı</b></th>
                            <th class="text-center"><b>Şirkət Emaili</b></th>
                            <th class="text-center"><b>Şirkət Telefonu</b></th>
                            <th class="text-center"><b>Şirkət Adresi</b></th>
                            <th class="text-center"><b>Şirkət tipi</b></th>
                            <th class="text-center"><b>Menecer Adı</b></th>
                            <th class="text-center"><b>Menecer soyadı</b></th>
                            <th class="text-center"><b>Menecer Emaili</b></th>
                            <th class="text-center"><b>Menecer Nömrəsi</b></th>
                            <th class="text-center"><b>Əlavə olunma tarixi</b></th>
                            <th class="text-center"><b>Əməliyyatlar</b></th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<form id="DataTableForm">@Html.AntiForgeryToken()</form>