Presentation/UTEP.Web/Areas/CompanyProfile/Controllers/DriverResponseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UTEP.Web.Areas.DriverProfile.Models.DriverResponseViewModels;
using UTEP.Data.Domain.Models.Tables.TrailerBasedGroup;
using UTEP.Core.UnitOfWork.Persistence;
using Microsoft.EntityFrameworkCore;
using UTEP.Data;
using UTEP.Settings;
using UTEP.Web.Attribute;
using UTEP.Data.Domain.Models.Tables.DriverBasedGroup;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using UTEP.Web.Controllers;

namespace UTEP.Web.Areas.CompanyrProfile.Controllers
{
    [Area("CompanyrProfile")]
    [Authorize(Roles = "Manager")]
    [Route("[area]/{lang:lang}/[controller]/[action]/{id?}")]
    public class DriverResponseController : BaseController
    {
        private readonly UnitOfWork _unitOfWork;
        public DriverResponseController(DbContextOptions<UTEPDbContext> contextOptions)
        {
            _unitOfWork = new UnitOfWork(new UTEPDbContext(contextOptions));
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [AjaxOnly]
        public IActionResult LoadData()
        {
            var draw = HttpContext.Request.Form["draw"].FirstOrDefault();
            var start = Request.Form["start"].FirstOrDefault();
            var length = Request.Form["length"].FirstOrDefault();
            var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
            var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
            var searchValue = Request.Form["search[value]"].FirstOrDefault();

            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;

            var list = _unitOfWork.DriverResponses.FindDataTable(x => x.Status == Status.Active, "az", skip, pageSize, sortColumn, sortColumnDirection, searchValue);
            return Json(new { draw = draw, recordsFiltered = list.RecordsFiltered, recordsTotal = list.RecordsTotal, data = list.Data });
        }

        //[HttpGet]
        //public IActionResult Create()
        //{
        //    var model = new CreateDriverResponseViewModel
        //    {
        //        Drivers = _unitOfWork.Drivers.Find(x => x.Status == Status.Active).Select(y => new SelectListItem
        //        {
        //            Value = y.Id.ToString(),
        //            Text = y.User.ToString()
        //        }),
        //        Trucks = _unitOfWork.Trucks.Find(x => x.Status == Status.Active).Select(y => new SelectListItem
        //        {
        //            Value = y.Id.ToString(),
        //            Text = y.RegistrationNumber
        //        }),
        //        Trailers = _unitOfWork.Trailers.Find(x => x.Status == Status.Active).Select(y => new SelectListItem
        //        {
        //            Value = y.Id.ToString(),
        //            Text = y.RegistrationNumber
        //        }),
        //        CompanyOrders = _unitOfWork.CompanyOrders.Find(x => x.Status == Status.Active).Select(y => new SelectListItem
        //        {
        //            Value = y.Id.ToString(),
        //            Text = y.Product.Name
        //        })
        //    };
        //    return View(model);
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult Create(CreateDriverResponseViewModel model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var DriverResponse = new DriverResponse
        //        {
        //            DriverId = model.DriverId,
        //            TruckId = model.TruckId,
        //            TrailerId = model.TrailerId,
        //            CompanyOrderId = model.CompanyOrderId,
        //            EndDate = model.EndDate,
        //            StartDate = model.StartDate,
        //            EstimatePrice = model.EstimatePrice,
        //            DayCount = model.DayCount,
        //        };
        //        _unitOfWork.DriverResponses.Add(DriverResponse);
        //        _unitOfWork.Complete();
        //        _unitOfWork.Dispose();
        //        return RedirectToAction("Index", new { id = "" });

        //    }
        //    model.Drivers = _unitOfWork.Drivers.Find(x => x.Status == Status.Active).Select(y => new SelectListItem
        //    {
        //        Value = y.Id.ToString(),
        //        Text = y.User.ToString()
        //    });
        //    model.Trucks = _unitOfWork.Trucks.Find(x => x.Status == Status.Active).Select(y => new SelectListItem
        //    {
        //        Value = y.Id.ToString(),
        //        Text = y.RegistrationNumber
        //    });
        //    model.Trailers = _unitOfWork.Trailers.Find(x => x.Status == Status.Active).Select(y => new SelectListItem
        //    {
        //        Value = y.Id.ToString(),
        //        Text = y.RegistrationNumber
        //    });
        //    model.CompanyOrders = _unitOfWork.CompanyOrders.Find(x => x.Status == Status.Active).Select(y => new SelectListItem
        //    {
        //        Value = y.Id.ToString(),
        //        Text = y.Product.Name
        //    });
        //    return View(model);
        //}

        //[HttpGet]
        //public IActionResult Edit(long id)
        //{
        //    var driverResponse = _unitOfWork.DriverResponses.Get(x => x.Id == id && x.Status == Status.Active);
        //    if (driverResponse != null)
        //    {
        //        var model = new EditDriverResponseViewModel
        //        {
        //            Id = driverResponse.Id,
        //            EndDate = driverResponse.EndDate,
        //            StartDate = driverResponse.StartDate,
        //            EstimatePrice = driverResponse.EstimatePrice,
        //            DayCount = driverResponse.DayCount,
        //            CompanyOrderId = driverResponse.CompanyOrderId,
        //            CompanyOrders = _unitOfWork.CompanyOrders.Find(x => x.Status == Status.Active).Select(y => new SelectListItem
        //            {
        //                Value = y.Id.ToString(),
        //                Text = y.Product.Name
        //            }),
        //            DriverId = driverResponse.DriverId,
        //            Drivers = _unitOfWork.Drivers.Find(x => x.Status == Status.Active).Select(y => new SelectListItem
        //            {
        //                Value = y.Id.ToString(),
        //                Text = y.User.FirstName + y.User.LastName
        //            }),
        //            TruckId = driverResponse.TruckId,
        //            Trucks = _unitOfWork.Trucks.Find(x => x.Status == Status.Active).Select(y => new SelectListItem
        //            {
        //                Value = y.Id.ToString(),
        //                Text = y.RegistrationNumber
        //            }),
        //            TrailerId = driverResponse.TrailerId,
        //            Trailers = _unitOfWork.Trailers.Find(x => x.Status == Status.Active).Select(y => new SelectListItem
        //            {
        //                Value = y.Id.ToString(),
        //                Text = y.RegistrationNumber
        //            })
        //        };
        //        return View(model);
        //    }
        //    return NotFound();
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult Edit(EditDriverResponseViewModel model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var driverResponse = _unitOfWork.DriverResponses.Get(x => x.Id == model.Id && x.Status == Status.Active);
        //        if (driverResponse != null)
        //        {
        //            driverResponse.EndDate = model.EndDate;
        //            driverResponse.StartDate = model.StartDate;
        //            driverResponse.DayCount = model.DayCount;
        //            driverResponse.EstimatePrice = model.EstimatePrice;

        //            driverResponse.DriverId = model.DriverId;
        //            driverResponse.TruckId = model.TruckId;
        //            driverResponse.TrailerId = model.TrailerId;
        //            driverResponse.CompanyOrderId = model.CompanyOrderId;
        //            driverResponse.CompanyOrderId = model.CompanyOrderId;
        //            try
        //            {
        //                _unitOfWork.DriverResponses.Update(driverResponse);
        //                _unitOfWork.Complete();
        //                _unitOfWork.Dispose();
        //                return RedirectToAction("Index", new { di = "" });
        //            }
        //            catch (Exception)
        //            {
        //                return RedirectToAction("Error", "Home", new { area = " " });
        //            }
        //        }
        //    }
        //    model.Drivers = _unitOfWork.Drivers.Find(x => x.Status == Status.Active).Select(y => new SelectListItem
        //    {
        //        Value = y.Id.ToString(),
        //        Text = y.User.ToString()
        //    });
        //    model.Trucks = _unitOfWork.Trucks.Find(x => x.Status == Status.Active).Select(y => new SelectListItem
        //    {
        //        Value = y.Id.ToString(),
        //        Text = y.RegistrationNumber
        //    });
        //    model.Trailers = _unitOfWork.Trailers.Find(x => x.Status == Status.Active).Select(y => new SelectListItem
        //    {
        //        Value = y.Id.ToString(),
        //        Text = y.RegistrationNumber
        //    });
        //    model.CompanyOrders = _unitOfWork.CompanyOrders.Find(x => x.Status == Status.Active).Select(y => new SelectListItem
        //    {
        //        Value = y.Id.ToString(),
        //        Text = y.ProporsalPrice.ToString()
        //    });

Presentation/UTEP.Web/Areas/DriverProfile/Views/DriverResponse/Create.cshtml
@model UTEP.Web.Areas.DriverProfile.Models.DriverResponseViewModels.CreateDriverResponseViewModel

@{
    ViewData["Title"] = "DriverResponse Yeni";
}

<div class="row">
    <div class="col-md-offset-2 col-md-8">
        <div class="profile-content">
            <div class="row">
                <div class="col-md-12">
                    <div class="portlet light bordered">
                        <div class="portlet-title tabbable-line">
                            <div class="caption caption-md">
                                <i class="icon-globe theme-font hide"></i>
                                <span class="caption-subject font-blue-madison bold uppercase">Yeni</span>
                            </div>
                            <ul class="nav nav-tabs">
                                <li class="active">
                                    <a href="#tab_1_1" data-toggle="tab">DriverResponse</a>
                                </li>
                            </ul>
                        </div>
                        <div class="portlet-body">
                            <div class="tab-content">
                                <!--  INFO TAB -->
                                <div class="tab-pane active" id="tab_1_1">

                                    <form asp-area="DriverProfile" asp-controller="DriverResponse" asp-action="Create" method="post">
                                        <div asp-validation-summary="All" class="text-danger"></div>
                                        <div class="form-group">
                                            <label class="control-label">Başlanğıc Tarix</label>
                                            <input asp-for="StartDate" autofocus class="form-control" />
                                            <span asp-validation-for="StartDate" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Son Tarix</label>
                                            <input asp-for="EndDate" asp-is-invariant="true" class="form-control">
                                            <span asp-validation-for="EndDate" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Gün Sayı</label>
                                            <input asp-for="DayCount" asp-is-invariant="true" class="form-control">
                                            <span asp-validation-for="DayCount" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Qiymət</label>
                                            <input asp-for="EstimatePrice" class="form-control">
                                            <span asp-validation-for="EstimatePrice" class="text-danger"></span>
                                        </div>
                                        @*<div class="form-group">
                                            <label class="control-label">Sürücü</label>
                                            <select asp-for="DriverId" asp-items="Model.Drivers" class="form-control"></select>
                                            <span asp-validation-for="DriverId" class="text-danger"></span>
                                        </div>*@
                                        <input asp-for="DriverId" type="hidden" value="@Model.DriverId" />
                                        <div class="form-group">
                                            <label class="control-label">Truck</label>
                                            <select asp-for="TruckId" asp-items="Model.Trucks" class="form-control"></select>
                                            <span asp-validation-for="TruckId" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Yük Hissəsi</label>
                                            <select asp-for="TrailerId" asp-items="Model.Trailers" class="form-control"></select>
                                            <span asp-validation-for="TrailerId" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Məhsul</label>
                                            <select asp-for="CompanyOrderId" asp-items="Model.CompanyOrders" class="form-control"></select>
                                            <span asp-validation-for="CompanyOrderId" class="text-danger"></span>
                                        </div>
                                        <div class="form-actions text-right">
                                            <button id="btn-validate-spinner" type="button" class="btn green">Təsdiqlə</button>
                                            <a asp-area="CompanyProfile" asp-controller="DriverResponse" asp-action="Index" asp-route-id="" class="btn default">Ləğv et</a>
                                        </div>
                                    </form>
                                </div>
                                <!-- End  TAB -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts{ <script src="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/datatables.min.js"></script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

}

Presentation/UTEP.Web/Areas/DriverProfile/Views/DriverResponse/Edit.cshtml
@model UTEP.Web.Areas.DriverProfile.Models.DriverResponseViewModels.EditDriverResponseViewModel

@{
    ViewData["Title"] = "DriverResponse Edit";
}

<div class="row">
    <div class="col-md-offset-2 col-md-8">
        <div class="profile-content">
            <div class="row">
                <div class="col-md-12">
                    <div class="portlet light bordered">
                        <div class="portlet-title tabbable-line">
                            <div class="caption caption-md">
                                <i class="icon-globe theme-font hide"></i>
                                <span class="caption-subject font-blue-madison bold uppercase">Edit</span>
                            </div>
                            <ul class="nav nav-tabs">
                                <li class="active">
                                    <a href="#tab_1_1" data-toggle="tab">DriverResponse</a>
                                </li>
                            </ul>
                        </div>
                        <div class="portlet-body">
                            <div class="tab-content">
                                <!--  INFO TAB -->
                                <div class="tab-pane active" id="tab_1_1">

                                    <form asp-area="companyprofile" asp-controller="DriverResponse" asp-action="Edit" method="post">
                                        <div asp-validation-summary="All" class="text-danger"></div>
                                        <div class="form-group">
                                            <label class="control-label">Başlanğıc Tarix</label>
                                            <input asp-for="StartDate" autofocus class="form-control" />
                                            <span asp-validation-for="StartDate" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Son Tarix</label>
                                            <input asp-for="EndDate" asp-is-invariant="true" class="form-control">
                                            <span asp-validation-for="EndDate" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Gün Sayı</label>
                                            <input asp-for="DayCount" asp-is-invariant="true" class="form-control">
                                            <span asp-validation-for="DayCount" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Qiymət</label>
                                            <input asp-for="EstimatePrice" class="form-control">
                                            <span asp-validation-for="EstimatePrice" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Sürücü</label>
                                            <select asp-for="DriverId" asp-items="Model.Drivers" class="form-control"></select>
                                            <span asp-validation-for="DriverId" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Truck</label>
                                            <select asp-for="TruckId" asp-items="Model.Trucks" class="form-control"></select>
                                            <span asp-validation-for="TruckId" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Yük Hissəsi</label>
                                            <select asp-for="TrailerId" asp-items="Model.Trailers" class="form-control"></select>
                                            <span asp-validation-for="TrailerId" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Məhsul</label>
                                            <select asp-for="CompanyOrderId" asp-items="Model.CompanyOrders" class="form-control"></select>
                                            <span asp-validation-for="CompanyOrderId" class="text-danger"></span>
                                        </div>
                                        <div class="form-actions text-right">
                                            <button id="btn-validate-spinner" type="button" class="btn green">Təsdiqlə</button>
                                            <a asp-area="CompanyProfile" asp-controller="DriverResponse" asp-action="Index" asp-route-id="" class="btn default">Ləğv et</a>
                                        </div>

                                    </form>
                                </div>
                                <!-- End  TAB -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts{ <script src="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/datatables.min.js"></script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

}

Presentation/UTEP.Web/Areas/DriverProfile/Views/DriverResponse/Index.cshtml
@{
    ViewData["Title"] = "Ana Sehife";
}

@*<html xmlns="http://www.w3.org/1999/xhtml">*@
<title></title>

@section Styles{ <link href="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" />

    <link href="~/Plugins/DataTables/DataTables-1.10.18/css/dataTables.bootstrap4.css" rel="stylesheet" />
    
}

@section Scripts{ <script src="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/datatables.min.js"></script>

    <script src="~/Plugins/DataTables/DataTables-1.10.18/js/jquery.dataTables.js"></script>
    <script src="~/Plugins/DataTables/DataTables-1.10.18/js/dataTables.bootstrap4.js"></script>
    <script src="~/js/date/formatdate.js"></script>
    <script src="~/js/admin/driverResponse.js"></script>
}

<div class="row margin-top-10">
    <div class="col-md-12 text-center">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-dark">
                    <i class="fab fa-driverResponse-hunt"></i>
                    <span class="caption-subject bold">
                        Sürücü Cavabı
                    </span>
                </div>
                <div class="tools"> </div>
            </div>
            <div class="portlet-body">
                <table id="driverresponseIndexTable" class="table table-hover table-striped table-bordered nowrap text-center" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th class="text-center"><b>Sürücü</b></th>
                            <th class="text-center"><b>Truck</b></th>
                            <th class="text-center"><b>Yük Hissə</b></th>
                            <th class="text-center"><b>Məhsul</b></th>
                            <th class="text-center"><b>Qiymət</b></th>
                            <th class="text-center"><b>Başlanğıc Tarix</b></th>
                            <th class="text-center"><b>Son Tarix</b></th>
                            <th class="text-center"><b>Gün Sayı</b></th>
                            <th class="text-center"><b>Əlavə olunma tarixi</b></th>
                            <th class="text-center"><b>Əməliyyatlar</b></th>
                        </tr>
                    </thead>

                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>