Presentation/UTEP.Web/Areas/CompanyProfile/Controllers/CompanyOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UTEP.Web.Areas.CompanyProfile.Models.CompanyOrderViewModels;
using UTEP.Core.UnitOfWork.Persistence;
using Microsoft.EntityFrameworkCore;
using UTEP.Data;
using UTEP.Settings;
using UTEP.Web.Attribute;
using Microsoft.AspNetCore.Mvc.Rendering;
using UTEP.Data.Domain.Models.Tables.CompanyBasedGroup;
using UTEP.Web.Areas.CompanyProfile.Models.ProductViewModels;
using UTEP.Data.Domain.Models.Tables.ProductBasedGroup;
using Microsoft.AspNetCore.Identity;
using UTEP.Data.Domain.Models.Tables.UserBasedGroup;
using Microsoft.AspNetCore.Http;
using UTEP.Web.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using UTEP.Web.Areas.CompanyProfile.Models;
using System.IO;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Drawing.Imaging;
using System.Drawing;
using Microsoft.Extensions.Localization;
using UTEP.Web.Controllers;

namespace UTEP.Web.Areas.CompanyProfile.Controllers
{
    [Area("CompanyProfile")]
    [Authorize(Roles = "Manager")]
    [Route("{lang:lang}/[area]/[controller]/[action]/{id?}")]
    public class CompanyOrderController : BaseController
    {
        private readonly UnitOfWork _unitOfWork;
        private readonly UserManager<User> _userManager;
        private readonly IStringLocalizer<CompanyOrderController> _localizer;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IEmailSender _emailSender;
        private readonly IFileProcessor _fileProcessor;
        public CompanyOrderController(
            DbContextOptions<UTEPDbContext> contextOptions,
            UserManager<User> userManager,
            IStringLocalizer<CompanyOrderController> localizer,
            IHostingEnvironment hostingEnvironment,
            IFileProcessor fileProcessor,
            IEmailSender emailSender
            )
        {
            _unitOfWork = new UnitOfWork(new UTEPDbContext(contextOptions));
            _localizer = localizer;
            _userManager = userManager;
            _hostingEnvironment = hostingEnvironment;
            _fileProcessor = fileProcessor;
            _emailSender = emailSender;
        }

        [HttpGet]
        public IActionResult Index()
        {
            ViewData["success"] = TempData["success"];
            return View();
        }

        [HttpPost]
        [AjaxOnly]
        public async Task<IActionResult> LoadData()
        {
            var lang = RouteData.Values["lang"].ToString() ?? "az";
            var user = await _userManager.GetUserAsync(User);

            var draw = HttpContext.Request.Form["draw"].FirstOrDefault();
            var start = Request.Form["start"].FirstOrDefault();
            var length = Request.Form["length"].FirstOrDefault();
            var sortColumn = Request.Form["columns[" + Request.Form["Order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
            var sortColumnDirection = Request.Form["Order[0][dir]"].FirstOrDefault();
            var searchValue = Request.Form["search[value]"].FirstOrDefault();
            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;
            var list = _unitOfWork.CompanyOrders.FindDataTable(x => x.Status == Status.Active && x.Products.FirstOrDefault().Company.UserId == user.Id, lang, skip, pageSize, sortColumn, sortColumnDirection, searchValue);
            return Json(new { draw = draw, recordsFiltered = list.RecordsFiltered, recordsTotal = list.RecordsTotal, data = list.Data });
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var lang = RouteData.Values["lang"].ToString();
            //var user = await _userManager.Users.FirstOrDefaultAsync(x => x.Company.Id == 2);  
            var user = await _userManager.GetUserAsync(User);
            var companyId = _unitOfWork.Companies.Get(x => x.UserId == user.Id).Id;
            var model = new CreateCompanyOrderViewModel
            {
                CreateProduct = new CreateProductViewModel
                {
                    CompanyId = companyId,
                    ProductTypes = _unitOfWork.ProductTypes.Find(x => x.Status == Status.Active).Select(x => new SelectListItem
                    {
                        Value = x.Id.ToString(),
                        Text = x.ProductTypeTranslations.First(y => y.SiteLanguage.LanguageCode == lang).Name
                    }),
                    PaletteCount = 1
                },
                FromCountries = _unitOfWork.Countries.Find(x => x.Status == Status.Active).OrderBy(x => x.Name).Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                }),
                ToCountries = _unitOfWork.Countries.Find(x => x.Status == Status.Active).OrderBy(x => x.Name).Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                }),
                Lang = lang
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateCompanyOrderViewModel model, IFormCollection files)
        {
            var lang = RouteData.Values["lang"].ToString() ?? "az";
            if (ModelState.IsValid)
            {
                if (files.Files.Count > 6)
                {
                    ModelState.AddModelError("", _localizer["6images_validate"]);
                    model.CreateProduct.ProductTypes = _unitOfWork.ProductTypes.Find(x => x.Status == Status.Active).Select(x => new SelectListItem
                    {
                        Value = x.Id.ToString(),
                        Text = x.ProductTypeTranslations.First(y => y.SiteLanguage.LanguageCode == lang).Name
                    });

                    model.FromCountries = _unitOfWork.Countries.Find(x => x.Status == Status.Active).OrderBy(x => x.Name).Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    });
                    model.FromCities = _unitOfWork.Cities.Find(x => x.Status == Status.Active && x.CountryId == model.FromCountryId).OrderBy(x => x.Name).Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    });

                    model.ToCountries = _unitOfWork.Countries.Find(x => x.Status == Status.Active).OrderBy(x => x.Name).Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    });
                    model.ToCities = _unitOfWork.Cities.Find(x => x.Status == Status.Active && x.CountryId == model.ToCountryId).OrderBy(x => x.Name).Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    });
                    return View(model);
                }
                if (files.Files.Count == 0)
                {
                    ModelState.AddModelError("", _localizer["image_required"]);
                    model.CreateProduct.ProductTypes = _unitOfWork.ProductTypes.Find(x => x.Status == Status.Active).Select(x => new SelectListItem
                    {
                        Value = x.Id.ToString(),
                        Text = x.ProductTypeTranslations.First(y => y.SiteLanguage.LanguageCode == lang).Name
                    });

                    model.FromCountries = _unitOfWork.Countries.Find(x => x.Status == Status.Active).OrderBy(x => x.Name).Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    });
                    model.FromCities = _unitOfWork.Cities.Find(x => x.Status == Status.Active && x.CountryId == model.FromCountryId).OrderBy(x => x.Name).Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    });

                    model.ToCountries = _unitOfWork.Countries.Find(x => x.Status == Status.Active).OrderBy(x => x.Name).Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    });
                    model.ToCities = _unitOfWork.Cities.Find(x => x.Status == Status.Active && x.CountryId == model.ToCountryId).OrderBy(x => x.Name).Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    });
                    return View(model);
                }
                if (model.DealDate > model.DeadLine)
                {
                    ModelState.AddModelError("", _localizer["start_end_validate"]);
                    model.CreateProduct.ProductTypes = _unitOfWork.ProductTypes.Find(x => x.Status == Status.Active).Select(x => new SelectListItem
                    {
                        Value = x.Id.ToString(),
                        Text = x.ProductTypeTranslations.First(y => y.SiteLanguage.LanguageCode == lang).Name
                    });

                    model.FromCountries = _unitOfWork.Countries.Find(x => x.Status == Status.Active).OrderBy(x => x.Name).Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    });

Presentation/UTEP.Web/Areas/CompanyProfile/Views/CompanyOrder/Index.cshtml
@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = Localizer["main"];
}

@section Styles{ <link href="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" />
    <link href="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" />
    @*<link href="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" />*@
    <link href="~/Plugins/DataTables/DataTables-1.10.18/css/dataTables.bootstrap4.css" rel="stylesheet" />
    <style>
        .swal-text {
            text-align: center !important;
        }
    </style>
}
<input type="hidden" class="swalMessage" value="@ViewData["success"]" />

@section Scripts{
    <script src="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/datatables.min.js"></script>
    <script src="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/datatables.min.js"></script>
    @*<script src="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js"></script>*@
    <script src="~/Plugins/DataTables/DataTables-1.10.18/js/jquery.dataTables.js"></script>
    <script src="~/Plugins/DataTables/DataTables-1.10.18/js/dataTables.bootstrap4.js"></script>
    <script src="~/js/date/formatdate.js"></script>
    <script src="~/js/admin/companyOrder.js"></script>
    <script>
        $(document).ready(function () {
            var message = $(".swalMessage").val();
            if (message != "") {
                swal('@Localizer["title"]', '@Localizer["success"]', 'success');
            }
        });
    </script>
}


<div class="row margin-top-10">
    <div class="col-md-12 text-center">
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-dark">
                    <i class="fa fa-briefcase font-dark"></i>
                    <span class="caption-subject bold">
                        @Localizer["my_announces"]
                        <a asp-controller="CompanyOrder" asp-action="Create" class="btn blue btn-xs  btn-outline">
                            @Localizer["new"] <i class="fa fa-plus"></i>
                        </a>
                        <a asp-controller="CompanyOrder" asp-action="Trash" class="btn red btn-xs  btn-outline">
                            @Localizer["deleted"] <i class="fa fa-times"></i>
                        </a>
                        <a asp-controller="CompanyOrder" asp-action="Waited" class="btn green btn-xs  btn-outline">
                            @Localizer["admin_not_confirmed"] <i class="fa fa-plus-circle"></i>
                        </a>
                    </span>
                </div>
            </div>
            <div class="portlet-body">
                <table id="companyorderIndexTable" class="table table-hover table-striped table-bordered nowrap text-center" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th class="text-center"><b>@Localizer["proporsalprice"]</b></th>
                            <th class="text-center"><b>@Localizer["valuta"]</b></th>
                            <th class="text-center"><b>@Localizer["start_place"]</b></th>
                            <th class="text-center"><b>@Localizer["end_place"]</b></th>
                            <th class="text-center"><b>@Localizer["name"]</b></th>
                            <th class="text-center"><b>@Localizer["tonnage"]</b></th>
                            <th class="text-center"><b>Sabit</b></th>
                            <th class="text-center"><b>@Localizer["count"]</b></th>
                            <th class="text-center"><b>@Localizer["start_date"]</b></th>
                            <th class="text-center"><b>@Localizer["end_date"]</b></th>
                            <th class="text-center"><b>@Localizer["add_date"]</b></th>
                            <th class="text-center"><b>@Localizer["operations"]</b></th>
                        </tr>
                    </thead>

                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<form id="DataTableForm">@Html.AntiForgeryToken()</form>

Presentation/UTEP.Web/Areas/CompanyProfile/Views/CompanyOrder/Trash.cshtml
@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = Localizer["deleted"];
}
<title></title>

@section Styles{ <link href="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" />
    <link href="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" />
    @*<link href="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" />*@
    <link href="~/Plugins/DataTables/DataTables-1.10.18/css/dataTables.bootstrap4.css" rel="stylesheet" />
}

@section Scripts{
    <script src="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/datatables.min.js"></script>
    <script src="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/datatables.min.js"></script>
    @*<script src="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js"></script>*@
    <script src="~/Plugins/DataTables/DataTables-1.10.18/js/jquery.dataTables.js"></script>
    <script src="~/Plugins/DataTables/DataTables-1.10.18/js/dataTables.bootstrap4.js"></script>
    <script src="~/js/date/formatdate.js"></script>
    <script src="~/js/admin/companyOrder.js"></script>
}


<div class="row margin-top-10">
    <div class="col-md-12 text-center">
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-dark">
                    <i class="fa fa-briefcase font-dark"></i>
                    <span class="caption-subject bold">
                        @Localizer["my_announces"]
                        <a asp-controller="CompanyOrder" asp-action="Create" class="btn blue btn-xs  btn-outline">
                            @Localizer["new"] <i class="fa fa-plus"></i>
                        </a>
                        <a asp-controller="CompanyOrder" asp-action="Index" class="btn yellow btn-xs  btn-outline">
                            @Localizer["list"] <i class="fa fa-list-ul"></i>
                        </a>
                        <a asp-controller="CompanyOrder" asp-action="Waited" class="btn green btn-xs  btn-outline">
                            @Localizer["admin_not_confirmed"] <i class="fa fa-plus-circle"></i>
                        </a>
                    </span>
                </div>
            </div>
            <div class="portlet-body">
                <table id="companyorderTrashTable" class="table table-hover table-striped table-bordered nowrap text-center" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th class="text-center"><b>@Localizer["proporsalprice"]</b></th>
                            <th class="text-center"><b>@Localizer["valuta"]</b></th>
                            <th class="text-center"><b>@Localizer["start_place"]</b></th>
                            <th class="text-center"><b>@Localizer["end_place"]</b></th>
                            <th class="text-center"><b>@Localizer["name"]</b></th>
                            <th class="text-center"><b>@Localizer["tonnage"]</b></th>
                            <th class="text-center"><b>Sabit</b></th>
                            <th class="text-center"><b>@Localizer["count"]</b></th>
                            <th class="text-center"><b>@Localizer["start_date"]</b></th>
                            <th class="text-center"><b>@Localizer["end_date"]</b></th>
                            <th class="text-center"><b>@Localizer["add_date"]</b></th>
                            <th class="text-center"><b>@Localizer["operations"]</b></th>
                        </tr>
                    </thead>

                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<form id="DataTableForm">@Html.AntiForgeryToken()</form>

Presentation/UTEP.Web/Areas/CompanyProfile/Views/CompanyOrder/Waited.cshtml
@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = "Təsdiq olunmayanlar məhsullar";
}

@section Styles{ <link href="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" />
    <link href="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" />
    @*<link href="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" />*@
    <link href="~/Plugins/DataTables/DataTables-1.10.18/css/dataTables.bootstrap4.css" rel="stylesheet" />
}

@section Scripts{
    <script src="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/datatables.min.js"></script>
    <script src="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/datatables.min.js"></script>
    @*<script src="~/952A9DBE-18BC-4A9E-8B71-8E4E2AE4C6C2/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js"></script>*@
    <script src="~/Plugins/DataTables/DataTables-1.10.18/js/jquery.dataTables.js"></script>
    <script src="~/Plugins/DataTables/DataTables-1.10.18/js/dataTables.bootstrap4.js"></script>
    <script src="~/js/date/formatdate.js"></script>
    <script src="~/js/admin/companyOrder.js"></script>
}


<div class="row margin-top-10">
    <div class="col-md-12 text-center">
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-dark">
                    <i class="fa fa-briefcase font-dark"></i>
                    <span class="caption-subject bold">
                        @Localizer["my_announces"]
                        <a asp-controller="CompanyOrder" asp-action="Create" class="btn blue btn-xs  btn-outline">
                            @Localizer["new"] <i class="fa fa-plus"></i>
                        </a>
                        <a asp-controller="CompanyOrder" asp-action="Trash" class="btn red btn-xs  btn-outline">
                            @Localizer["deleted"] <i class="fa fa-remove"></i>
                        </a>
                        <a asp-controller="CompanyOrder" asp-action="Index" class="btn yellow btn-xs  btn-outline">
                            @Localizer["list"] <i class="fa fa-list-ul"></i>
                        </a>
                    </span>
                </div>
            </div>
            <div class="portlet-body">
                <table id="companyorderWaitedTable" class="table table-hover table-striped table-bordered nowrap text-center" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th class="text-center"><b>@Localizer["proporsalprice"]</b></th>
                            <th class="text-center"><b>@Localizer["valuta"]</b></th>
                            <th class="text-center"><b>@Localizer["start_place"]</b></th>
                            <th class="text-center"><b>@Localizer["end_place"]</b></th>
                            <th class="text-center"><b>@Localizer["name"]</b></th>
                            <th class="text-center"><b>@Localizer["tonnage"]</b></th>
                            <th class="text-center"><b>Sabit</b></th>
                            <th class="text-center"><b>@Localizer["count"]</b></th>
                            <th class="text-center"><b>@Localizer["start_date"]</b></th>
                            <th class="text-center"><b>@Localizer["end_date"]</b></th>
                            <th class="text-center"><b>@Localizer["add_date"]</b></th>
                        </tr>
                    </thead>

                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>